### ISSUE TITLE
Detected blocking call to load_verify_locations with args (<ssl.SSLContext object at 0x7f5802f2d0>,) 

### ISSUE THREAD

**Issue by jrkk0925** [ankohanse/hass-dab-pumps#38] opened 2024-09-09 22:08 UTC
Core
2024.9.1
Supervisor
2024.08.0
Operating System
13.1
Frontend
20240906.0
 
Getting these error after restarts of home assistant.

Detected blocking call to load_verify_locations with args (<ssl.SSLContext object at 0x7f5802f2d0>,) inside the event loop by custom integration 'dabpumps' at custom_components/dabpumps/api.py, line 166: client = httpx.AsyncClient(follow_redirects=True, timeout=120.0) (offender: /usr/local/lib/python3.12/site-packages/httpx/_config.py, line 147: context.load_verify_locations(cafile=cafile)), please create a bug report at https://github.com/ankohanse/hass-dab-pumps/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_verify_locations Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component result = await _async_setup_component(hass, domain, config) File "/usr/src/homeassistant/homeassistant/setup.py", line 461, in _async_setup_component await asyncio.gather( File "/usr/src/homeassistant/homeassistant/setup.py", line 463, in <genexpr> create_eager_task( File "/usr/src/homeassistant/homeassistant/util/async_.py", line 45, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 752, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/dabpumps/__init__.py", line 85, in async_setup_entry await coordinator.async_config_entry_first_refresh() File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 281, in async_config_entry_first_refresh await self._async_refresh( File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh self.data = await self._async_update_data() File "/config/custom_components/dabpumps/coordinator.py", line 225, in _async_update_data await self._async_detect_data() File "/config/custom_components/dabpumps/coordinator.py", line 302, in _async_detect_data await self._api.async_login() File "/config/custom_components/dabpumps/api.py", line 135, in async_login client = await self.async_login_dablive_app(isDabLive=1) File "/config/custom_components/dabpumps/api.py", line 166, in async_login_dablive_app client = httpx.AsyncClient(follow_redirects=True, timeout=120.0)

**Comment by ankohanse** [comment] 2024-09-09 22:24
Thank you for reporting this issue. I will look into it and try to find the cause.

**Comment by ankohanse** [comment] 2024-09-10 04:26
Fixed in release v2024.09.1 which I published a minute ago.

**Closed by ankohanse** 2024-09-10 04:26 UTC
Labels: invalid
